[project]
name = "twitchbotpython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.4",
    "irc>=20.5.0",
    "pyside6>=6.9.1",
    "sqlalchemy>=2.0.41",
]
