"""1/

Revision ID: eace4c4cc1c5
Revises: 
Create Date: 2023-08-26 12:28:50.724235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eace4c4cc1c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('irc_nickname', sa.String(), nullable=False),
    sa.Column('irc_token', sa.String(), nullable=False),
    sa.Column('irc_channel', sa.String(), nullable=False),
    sa.Column('sound_reward_id', sa.String(), nullable=False),
    sa.Column('blog_export_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('viewers',
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('hide_tracking', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewers')
    op.drop_table('settings')
    # ### end Alembic commands ###
