"""2/

Revision ID: f7685d9787e0
Revises: eace4c4cc1c5
Create Date: 2025-08-09 01:59:49.329965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7685d9787e0'
down_revision: Union[str, None] = 'eace4c4cc1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('client_id', sa.String(), server_default='', nullable=False))
    op.add_column('settings', sa.Column('client_secret', sa.String(), server_default='', nullable=False))
    op.add_column('settings', sa.Column('channel', sa.String(), server_default='', nullable=False))
    op.drop_column('settings', 'irc_token')
    op.drop_column('settings', 'irc_channel')
    op.drop_column('settings', 'irc_nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('irc_nickname', sa.VARCHAR(), nullable=False))
    op.add_column('settings', sa.Column('irc_channel', sa.VARCHAR(), nullable=False))
    op.add_column('settings', sa.Column('irc_token', sa.VARCHAR(), nullable=False))
    op.drop_column('settings', 'channel')
    op.drop_column('settings', 'client_secret')
    op.drop_column('settings', 'client_id')
    # ### end Alembic commands ###
