"""empty message

Revision ID: 115515cf1d8c
Revises: 
Create Date: 2018-12-27 19:17:43.304845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115515cf1d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_points',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_user_points_points'), 'user_points', ['points'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_points_points'), table_name='user_points')
    op.drop_table('user_points')
    # ### end Alembic commands ###
