"""empty message

Revision ID: b1a5f389ec5a
Revises: c9f5dabeded4
Create Date: 2023-08-25 21:05:58.342582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a5f389ec5a'
down_revision: Union[str, None] = 'c9f5dabeded4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewers',
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('hide_tracking', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewers')
    # ### end Alembic commands ###
